services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    networks:
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=emmanueltweve09@gmail.com
    networks:
      - nginx-proxy

  mongo-db:
    image: mongo:5.0.2
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=EmmanuelTweve09
      - MONGO_INITDB_ROOT_PASSWORD=Elementrix2030
    volumes:
      - energyquota:/data/db
    restart: unless-stopped
    networks:
      - nginx-proxy

  nodejs-app:
    depends_on:
      - mongo-db
    build:
      context: ../energyquota1
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGO_DB_URI=mongodb://EmmanuelTweve09:Elementrix2030@mongo-db:27017/energyQuotaDB?authSource=admin
      - SESSION_SECRETE="Elementrix2030"
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USER=elementrixtweve09@gmail.com
      - EMAIL_PASSWORD=rdzc hlqk vwyp yxgb
      - FRONTEND_URL=https://www.phociexperttechnologies.co.tz
      - VIRTUAL_HOST=www.phociexperttechnologies.co.tz, phociexperttechnologies.co.tz
      - LETSENCRYPT_HOST=www.phociexperttechnologies.co.tz,phociexperttechnologies.co.tz
    restart: unless-stopped
    networks:
      - nginx-proxy

volumes:
  conf: {}
  vhost: {}
  html: {}
  dhparam: {}
  certs: {}
  acme: {}
  energyquota:
    driver: local

networks:
  nginx-proxy: {}
